#
# path: /crates/engine_types/Cargo.toml
# description: Cargo manifest for the engine_types crate
#

[package]
name = "engine_types"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.24.0"

